
CREATE TABLE PAIS
(
IDPAIS INT NOT NULL IDENTITY(1,1),
NOMBRE VARCHAR(25) NOT NULL DEFAULT'',
CONSTRAINT PK_PAIS PRIMARY KEY(IDPAIS)
)

CREATE TABLE ESTADO
(
IDESTADO INT NOT NULL IDENTITY(1,1),
NOMBRE VARCHAR(25) NOT NULL,
ABREVIATURA VARCHAR(5) NOT NULL DEFAULT '',
CONSTRAINT PK_ESTADO PRIMARY KEY(IDESTADO)
)

CREATE TABLE CIUDAD
(
IDCIUDAD INT NOT NULL IDENTITY(1,1),
NOMBRE VARCHAR(25) NOT NULL DEFAULT '',
CONSTRAINT PK_CIUDAD PRIMARY KEY(IDCIUDAD)
)
 
CREATE TABLE PAIS_ESTADO
(
IDPAIS INT NOT NULL,
IDESTADO INT NOT NULL,
CONSTRAINT PK_PAIS_ESTADO PRIMARY KEY (IDPAIS, IDESTADO),

CONSTRAINT FK_PAIS_ESTADO_PAIS FOREIGN KEY (IDPAIS)
REFERENCES PAIS (IDPAIS) ON DELETE NO ACTION
ON UPDATE CASCADE,

CONSTRAINT FK_PAIS_ESTADO_ESTADO FOREIGN KEY (IDESTADO)
REFERENCES ESTADO (IDESTADO) ON DELETE NO ACTION
ON UPDATE CASCADE
)

CREATE TABLE ESTADO_CIUDAD
(
IDESTADO INT NOT NULL,
IDCIUDAD INT NOT NULL,
CONSTRAINT PK_ESTADO_CIUDAD PRIMARY KEY (IDESTADO, IDCIUDAD),

CONSTRAINT FK_ESTADO_CIUDAD_ESTADO FOREIGN KEY (IDESTADO)
REFERENCES ESTADO (IDESTADO) ON DELETE NO ACTION
ON UPDATE CASCADE,

CONSTRAINT FK_ESTADO_CIUDAD_CIUDAD FOREIGN KEY (IDCIUDAD)
REFERENCES CIUDAD (IDCIUDAD) ON DELETE NO ACTION
ON UPDATE CASCADE
)

CREATE TABLE CLASIFICACIONES
(
IDCLASIFICACION TINYINT NOT NULL IDENTITY(1, 1),
DESCRIPCION VARCHAR(25) NOT NULL DEFAULT '',
CONSTRAINT PK_CLASIFICACIONES PRIMARY KEY (IDCLASIFICACION)
)

CREATE TABLE GENEROS
(
IDGENERO TINYINT NOT NULL IDENTITY(1, 1),
DESCRIPCION VARCHAR(25) NOT NULL,
CONSTRAINT PK_GENEROS PRIMARY KEY (IDGENERO)
)

CREATE TABLE IDIOMAS
(
IDIDIOMA INT NOT NULL IDENTITY(1, 1),
NOMBREIDIOMA VARCHAR(25) NOT NULL,
CONSTRAINT PK_IDIOMA PRIMARY KEY (IDIDIOMA)
)

CREATE TABLE DESARROLLADORES
(
IDDESARROLLADOR INT NOT NULL IDENTITY(1, 1),
NOMBRE VARCHAR(50) NOT NULL,
IDPAIS INT NOT NULL DEFAULT '',
IDESTADO INT NOT NULL DEFAULT '',
IDCIUDAD INT NOT NULL DEFAULT '',
CONSTRAINT PK_DESARROLLADORES PRIMARY KEY (IDDESARROLLADOR)
)

CREATE TABLE DISTRIBUIDORES
(
IDDISTRIBUIDOR INT NOT NULL IDENTITY(1, 1),
NOMBRE VARCHAR(50) NOT NULL,
IDPAIS INT NOT NULL DEFAULT '',
IDESTADO INT NOT NULL DEFAULT '',
IDCIUDAD INT NOT NULL DEFAULT '',
CONSTRAINT PK_DISTRIBUIDORES PRIMARY KEY (IDDISTRIBUIDOR)
)

CREATE TABLE SISTEMASOPERATIVOS
(
IDSISTEMAOPERATIVO TINYINT NOT NULL IDENTITY(1, 1),
NOMBRE VARCHAR(50) NOT NULL,
CONSTRAINT PK_SISTEMASOPERATIVOS PRIMARY KEY (IDSISTEMAOPERATIVO)
)

CREATE TABLE JUEGOS
(
IDJUEGO INT NOT NULL IDENTITY(1, 1),
NOMBRE VARCHAR(100) NOT NULL,
FECHALANZAMIENTO DATETIME NOT NULL DEFAULT GETDATE(),
IDDESARROLLADORES INT NOT NULL,
IDCLASIFICACION TINYINT NOT NULL,
IDDISTRIBUIDOR INT NOT NULL,
PRECIO MONEY NOT NULL,
CONSTRAINT PK_JUEGOS PRIMARY KEY (IDJUEGO),

CONSTRAINT FK_JUEGOS_DESARROLLADORES FOREIGN KEY(IDDESARROLLADORES)
REFERENCES DESARROLLADORES (IDDESARROLLADOR) ON DELETE NO ACTION 
ON UPDATE NO ACTION,


CONSTRAINT FK_JUEGOS_CLASIFICACION FOREIGN KEY(IDCLASIFICACION)
REFERENCES CLASIFICACIONES (IDCLASIFICACION) ON DELETE NO ACTION 
ON UPDATE NO ACTION,

CONSTRAINT FK_JUEGOS_DISTRIBUIDOR FOREIGN KEY(IDDISTRIBUIDOR)
REFERENCES DISTRIBUIDORES (IDDISTRIBUIDOR) ON DELETE NO ACTION 
ON UPDATE NO ACTION
)

CREATE TABLE JUEGOS_SISTEMASOPERATIVOS
(
IDJUEGO INT NOT NULL,
IDSISTEMAOPERATIVO TINYINT NOT NULL,
CONSTRAINT PK_JUEGOS_SISTEMASOPERATIVOS PRIMARY KEY (IDJUEGO, IDSISTEMAOPERATIVO),

CONSTRAINT FK_JUEGOS_SISTEMASOPERATIVOS_JUEGO FOREIGN KEY (IDJUEGO)
REFERENCES JUEGOS (IDJUEGO) ON DELETE NO ACTION
ON UPDATE NO ACTION,

CONSTRAINT FK_JUEGOS_SISTEMASOPERATIVOS_SISTEMAOPERATIVO FOREIGN KEY (IDSISTEMAOPERATIVO)
REFERENCES SISTEMASOPERATIVOS (IDSISTEMAOPERATIVO) ON DELETE NO ACTION
ON UPDATE NO ACTION
)

CREATE TABLE JUEGOS_GENEROS
(
IDJUEGO INT NOT NULL,
IDGENERO TINYINT NOT NULL,
CONSTRAINT PK_JUEGOS_GENEROS PRIMARY KEY (IDJUEGO, IDGENERO),

CONSTRAINT FK_JUEGOS_GENEROS_JUEGO FOREIGN KEY (IDJUEGO)
REFERENCES JUEGOS (IDJUEGO) ON DELETE NO ACTION
ON UPDATE NO ACTION,

CONSTRAINT FK_JUEGOS_GENEROS_GENERO FOREIGN KEY (IDGENERO)
REFERENCES GENEROS (IDGENERO) ON DELETE NO ACTION
ON UPDATE NO ACTION
)

CREATE TABLE JUEGOS_IDIOMAS
(
IDJUEGO INT NOT NULL,
IDIDIOMA INT NOT NULL,
CONSTRAINT PK_JUEGOS_IDIOMAS PRIMARY KEY (IDJUEGO, IDIDIOMA),

CONSTRAINT FK_JUEGOS_IDIOMAS_JUEGO FOREIGN KEY (IDJUEGO)
REFERENCES JUEGOS (IDJUEGO) ON DELETE NO ACTION
ON UPDATE NO ACTION,

CONSTRAINT FK_JUEGOS_IDIOMAS_IDIOMA FOREIGN KEY (IDIDIOMA)
REFERENCES IDIOMAS (IDIDIOMA) ON DELETE NO ACTION
ON UPDATE NO ACTION
)

CREATE TABLE IMAGENES
(
IDIMAGEN INT NOT NULL IDENTITY(1, 1),
IMAGEN IMAGE NOT NULL,
CONSTRAINT PK_IMAGENES PRIMARY KEY (IDIMAGEN)
)

CREATE TABLE USUARIOS
(
IDUSUARIO INT NOT NULL IDENTITY(1, 1),
NOMBREPERFIL VARCHAR(50) NOT NULL,
NOMBREREAL VARCHAR(100) NOT NULL,
FECHANACIMIENTO DATE NOT NULL,
CORREOELECTRONICO VARCHAR(255) NOT NULL,
DESCRIPCION VARCHAR(255) NOT NULL DEFAULT '',
IDPAIS INT NOT NULL DEFAULT '',
IDESTADO INT NOT NULL DEFAULT '',
IDCIUDAD INT NOT NULL DEFAULT '',
IDIMAGEN INT NOT NULL,
CONSTRAINT PK_USUARIOS PRIMARY KEY (IDUSUARIO),

CONSTRAINT FK_USUARIO_IMAGEN FOREIGN KEY(IDIMAGEN)
REFERENCES IMAGENES(IDIMAGEN)ON DELETE NO ACTION 
ON UPDATE NO ACTION,

CONSTRAINT FK_USUARIO_PAIS FOREIGN KEY(IDPAIS)
REFERENCES PAIS(IDPAIS)ON DELETE NO ACTION 
ON UPDATE NO ACTION,

CONSTRAINT FK_USUARIO_ESTADO FOREIGN KEY(IDESTADO)
REFERENCES ESTADO(IDESTADO)ON DELETE NO ACTION 
ON UPDATE NO ACTION,

CONSTRAINT FK_USUARIO_CIUDAD FOREIGN KEY(IDCIUDAD)
REFERENCES CIUDAD(IDCIUDAD)ON DELETE NO ACTION 
ON UPDATE NO ACTION
)

CREATE TABLE METODOPAGO
(
IDMETODOPAGO TINYINT NOT NULL IDENTITY(1, 1),
DESCRIPCION VARCHAR(25) NOT NULL,
CONSTRAINT PK_METODOPAGO PRIMARY KEY (IDMETODOPAGO)
)

CREATE TABLE VENTAS
(
IDVENTA INT NOT NULL IDENTITY(1, 1),
FECHAVENTA DATE NOT NULL DEFAULT GETDATE(),
IDMETODOPAGO TINYINT NOT NULL,
IDUSUARIO INT NOT NULL
CONSTRAINT PK_VENTA PRIMARY KEY (IDVENTA),

CONSTRAINT FK_VENTAS_METODOPAGO FOREIGN KEY (IDMETODOPAGO)
REFERENCES METODOPAGO(IDMETODOPAGO) ON DELETE NO ACTION
ON UPDATE NO ACTION,

CONSTRAINT FK_VENTAS_USUARIO FOREIGN KEY (IDUSUARIO)
REFERENCES USUARIOS (IDUSUARIO) ON DELETE NO ACTION
ON UPDATE NO ACTION
)

CREATE TABLE VENTAS_JUEGOS
(
IDVENTA INT NOT NULL,
IDJUEGO INT NOT NULL,
CONSTRAINT PK_VENTAS_JUEGOS PRIMARY KEY (IDVENTA, IDJUEGO),

CONSTRAINT FK_VENTAS_JUEGOS_VENTA FOREIGN KEY (IDVENTA)
REFERENCES VENTAS (IDVENTA) ON DELETE NO ACTION
ON UPDATE NO ACTION,

CONSTRAINT FK_VENTAS_JUEGOS_JUEGO FOREIGN KEY (IDJUEGO)
REFERENCES JUEGOS (IDJUEGO) ON DELETE NO ACTION
ON UPDATE NO ACTION
)